### PR TITLE
CSS Transition

### PR DESCRIPTION
**Pull request by mayurankv**
The PR addresses the css changes we've been discussing and this also deals with the delay to reading mode updates (it is now  instant apart from changing non-pure css settings like enabling/disabling line numbers or changing highlighted lines).

 As I said I'm not familiar with javascript development so I wasn't sure where to hook the new function `updateSettingStyles` so it may be being called a bit more frequently than it needs to be. A proper refactor may be beneficial going forwards as specifically the `CodeblockCustomizerColors` interface is not respected and altering the structure of settings would reduce much of the complexity in the `updateSettingStyles` function. Furthermore, I reduced the number of classes applied by applying the styling for rounding corners etc. in pure css. This means that a lot of the cases you were considering are irrelevant but I didn't change these myself so they should be able to be simplified quite a bit.

Unfortunately, this has led to some annoying behaviour where when you turn on/off line numbering, the gutter colors and spacing in reading mode change instantly whilst the lines of code and numbers only appear after a re-render (the old delayed update problem). This (and the whole delay problem) can be fixed by extending what I've currently done to making the icons, headers and numbers turned on and off via css properties rather than in html. (I will try and work on that soon)

I also left a few comments with questions I hope you can answer.

Sorry for the rather large changes and apologies if I've done something wrong with this, it's my first PR.

Anyway, please let me know if you have any thoughts!

### CODE REVIEW

**Comment by mugiwara85** [comment]
Are you done, or are you planning to make more changes? I don't want to start reviewing it, until you are finished. This will take a huge amount of time, and I need to fix the bugs you introduced (don't worry, there are not much, just a few) :)

**Comment by mayurankv** [comment]
Sorry, give me just a little bit longer! I've made some wider changes that address most of the issues I've fixed above but I'm stuck with one particularly annoying bug.

The plugin currently, it waits for `language-` codeblocks to have loaded to make changes to those and that works fine. But on first load of Obsidian (not re-render of the page) non-specified codeblocks (so `\`\`\``) which are processed without any waiting get initially styled properly, then suddenly change from 

```html
<code>
  <div>
    <div class="line-number">1</div>
    <div class="line-text">foo</div>
  </div>
<code>
``` 

to just 

```
<code class="language-none">1foo</code>
```

I've tried following it in the debugger but I can't work out why this happens.

If I wait for a second before styling the none-language codeblocks it works just fine on loading obsidian (but then takes a second to render everytime you open a new file). The issue is literally only after reloading the whole of obsidian, not opening notes for the first time.

I've never seen this `language-none` so I'm not sure how to deal with it?

**Comment by mugiwara85** [comment]
Sure, no problem. Language-none is, when there is no language specified in the code block. And yes, you have to wait a little, otherwise, the syntax highlighting loads, and reverses the modifications

**Comment by mayurankv** [comment]
All fixed now, should be ready to push within the hour.

**Comment by mayurankv** [comment]
(Also out of curiosity haha, what are the bugs?)

**Comment by mayurankv** [comment]
I also haven't found a pure css issue, for the too large line numbers in source mode (Live Preview). Currently just letting it scroll but this looks pretty bad. I think some dynamic javascript is needed but whenever I tried to extract the width of the elements it was larger than it is in the console editor (think this is width pre- inserting into Obsidian leaf?). Maybe you can sort this. Reading mode is done though!

**Comment by mugiwara85** [comment]
> I also haven't found a pure css issue, for the too large line numbers in source mode (Live Preview). Currently just letting it scroll but this looks pretty bad. I think some dynamic javascript is needed but whenever I tried to extract the width of the elements it was larger than it is in the console editor (think this is width pre- inserting into Obsidian leaf?). Maybe you can sort this. Reading mode is done though!

Yeah, line numbers one was thing. The second was that if you force the header, it will be displayed if there is no language defined, and for code blocks which do not have a languge defined were some styles not aplpying. This is what I saw yesterday. But maybe you already corrected it :)
Let me know, if you are finished, and then I can check everything.

**Comment by mayurankv** [comment]
I've finished now! (I've been committing to master so I don't think I need to reopen a PR?).

Should have fixed a lot of things to be honest.

**Comment by mayurankv** [comment]
For the ln: parameter I've left comments where to hook that in and how I would do it. I also left some general comments and a toDo.md with some ideas.

**Comment by mayurankv** [comment]
Fixed the reading mode line numbers and no-language styling.
What do you mean, if you force the header it will be displayed without a language defined? Isn't this intended behaviour? What if someone sets fold on a no-language codeblock or a file name etc. Shouldn't the header be independent of language? That is what the setting `Display codeblock language (if language is defined)` is for no?

**Comment by mugiwara85** [comment]
> Fixed the reading mode line numbers and no-language styling. What do you mean, if you force the header it will be displayed without a language defined? Isn't this intended behaviour? What if someone sets fold on a no-language codeblock or a file name etc. Shouldn't the header be independent of language? That is what the setting `Display codeblock language (if language is defined)` is for no?

If you enable the marked two settings:
image

Then it displays (or yesterday this was the case) the header like this:
image

The first two code blocks do not have a language defined, therefore it makes no sense to display the header, because if no language is defined then there is no text to display, and there is also no icon to display.

**Comment by mayurankv** [comment]
Oh sorry! That's fixed now as well.

**Comment by mayurankv** [comment]
If any issues arise let me know!

**Comment by mugiwara85** [comment]
No, worries, I just noticed it yesterday. I start reviewing anything and add my code as well. Thank you very much for your effort. Is honestly much much more then I expected!

**Comment by mayurankv** [comment]
Ah no worries, I've been meaning to learn how to make obsidian plugins and typescript in general so this was as good an introduction as any!

**Comment by mugiwara85** [comment]
> Ah no worries, I've been meaning to learn how to make obsidian plugins and typescript in general so this was as good an introduction as any!

Depending on what you want to do with your plugin, it is not that difficult. The problematic part is when you want to do something in live preview mode. It uses CodeMirror 6, and that makes things more problematic. It took me a long time to get everything working as I wanted.

**Comment by mayurankv** [comment]
Oh its nothing specific but even making PRs for issues I want fixed in other plugins would be great lol. Aha I can imagine, it seemed a bit confusing.

When/if you merge/release this let me know. Hoping to do a quick refactor to make things clearer for the future.

**Comment by mugiwara85** [comment]
> Oh its nothing specific but even making PRs for issues I want fixed in other plugins would be great lol. Aha I can imagine, it seemed a bit confusing.
> 
> When/if you merge/release this let me know. Hoping to do a quick refactor to make things clearer for the future.

Ok, will do. I'm currently testing :)

**Comment by mugiwara85** [comment]
Basically, almost everything works fine, however, I found the following problems/questions:
- These two settings do not work as they should:
image
Now, they do nothing. If both are turned on, then the header is displayed for those code blocks as well, where no language is defined, whereas the header should not be displayed in these cases.
image

Why did you add scroll here? This causes the line numbers to display in editing mode incorrectly.
```css
.markdown-source-view .codeblock-customizer-line-number {
  overflow: scroll;
}
```
image

- Disabling the icon or the language leaves an empty space in the header:
image

- Collapsing the code removes the line and applies border radius to the header:
image
I find the old display better:
image


- The language tag does not reach the top (this is also true for the icon, and the text as well):
image

**Comment by mugiwara85** [comment]
Oh, and the themes do not work at all.

**Comment by mayurankv** [comment]
Oh hmmm, that is weird, I definitely thought I'd ironed out some of those bugs. I'll do some testing tmrw.

**Comment by mayurankv** [comment]
Sorry been a bit busy, I'll try and have a look tommorrow morning.

**Comment by mayurankv** [comment]
I actually have no issues at all with the scrolling in a plain vault with a new git clone? Could you confirm that it is definitely not a result of other snippets or plugins? If not could you show me better the issue in your vault and show how the scrolling works for those low numbers? I added the scroll as a temporary fix for line offset being massive. This way if it is 8000000, you still just see the rightmost numbers 001 002 003 and so on which is the best temporary fix I could come up with.

image

**Comment by mayurankv** [comment]
I'm happy to revert the collapsed headers but I find the border radius on the bottom to be much better visually when collapsed. Sometimes I'd have a collapsed codeblock followed by one without a header and be confused why the header was detached even though they were two separate blocks. 

I've disabled the padding that was previously implemented causing your last issue of not reaching the top (this was a choice I added but I agree it might be better to just remove). Have another look now that the padding is gone and see whether the collapsed codeblock appears how you want.

I'm very happy to revert the styling as I can always just add it for myself as a snippet but I do believe it looks better this way.

**Comment by mayurankv** [comment]
Also back to the line numbers, what are the weird lines by the side of your numbers (to the left)? I can't figure it out or recreate that.

**Comment by mayurankv** [comment]
(I'm also planning to add a collapsed indicator in the future so an arrow sideways when collapsed and an arrow down when not collapsed).

**Comment by mayurankv** [comment]
Fixed the padding issue when no icon.

**Comment by mugiwara85** [comment]
No, it is not a result of snippets or anything. I created a new vault just to be sure, but it is still the same. This issue with line numbers only happens in editor mode. Here is a short video about it:

https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/db2ec40b-33ed-4802-b2fb-8df8f4989a7a

I found a small issue. If you force the header by either selecting always display code block language/icon, then the padding is applied to the first line, where it should not:
image

The `Always display codeblock language` option still not work unfortunately. It still displays an empty header when there is no language defined. The `Always display codeblock language icon`

I also wanted to add a collapse indicator, I just haven't had the time for it :)

**Comment by mugiwara85** [comment]
@mayurankv Hey, I just wanted to ask, are you still working on this?

**Comment by mayurankv** [comment]
Hi, sorry! Had something come up. I'll do some incremental commits to fix the issues within the next few days! Sorry for the delay.

**Comment by mayurankv** [comment]
#16 Should be checked if it is resolved after the CSS changes as well.

**Comment by mayurankv** [comment]
Also would you be ok with the changing of the theming? Currently, the two default themes (light and dark) only differ in background color, header color, default highlight color, gutter color, gutter text color and header line color. 

All of these could be set for light and dark themes as with the alternative highlighting colors. This would make a much more understandable settings for light and dark themes in my opinion. Then each use theme is also applicable to light and dark mode. Do you have anythoughts?

The default background color and gutter color would be set to that of the theme to cause minimal visual change on first install. I think this make a lot of sense as it can be jarring to install and suddenly all codeblocks have a solarised-esque theme.

**Comment by mayurankv** [comment]
To complete this PR, I need to actually restructure this PR into branches so I'm going to revert main and turn this into feature branches so I'll need to change the PR as well sorry.

The plan is to fix the issues in the PR only. Then the new release can be submitted, then I can refactor the plugin a bit and add the default behaviour and things.

**Comment by mugiwara85** [comment]
> To complete this PR, I need to actually restructure this PR into branches so I'm going to revert main and turn this into feature branches so I'll need to change the PR as well sorry.
> 
> The plan is to fix the issues in the PR only. Then the new release can be submitted, then I can refactor the plugin a bit and add the default behaviour and things.

Sorry, I don't follow. Why do you need to restructure the PR to branches?

**Comment by mayurankv** [comment]
It'll be a lot easier to merge some other refactoring work and tbh the way I used commits so far has been a bit atrocious so basically gonna continue this just as a feature branch.

**Pull request closed without merging**
